Algoritmo "tabuada"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Prof. Dr. Nelio Alves
// Aluno    : Tiago de Paula Damasceno
// Data atual  : 12/02/2022

Var

   x, i, mult : inteiro

Inicio
   escreva("Deseja a tabuada para qual valor? ")
   leia(x)

   para i de 1 ate 10 faca
      mult <- i * x
      escreval(x, " x ", i, " = ", mult)
   fimpara
      
   


Fimalgoritmo